---
version: '3'
services:
  ft-dryrun-01:
    container_name: ft-dryrun-01
    build: .
    env_file: 
      - ./ft-dryrun-01.env
    restart: unless-stopped
    volumes:
      - "./db:/freqtrade/user_data/db"
    command: >
      freqtrade trade -c live.json -c user_data/blacklist-binance.json -c user_data/pairlist-volume-binance-BUSD.json
    networks:
      - pri_freq
  ft-dryrun-02:
    container_name: ft-dryrun-02
    build: .
    env_file: 
      - ./ft-dryrun-02.env
    restart: unless-stopped
    volumes:
      - "./db:/freqtrade/user_data/db"
    command: >
      freqtrade trade -c live.json -c user_data/blacklist-binance.json -c user_data/pairlist-volume-binance-BUSD.json
    networks:
      - pri_freq
    
  # caddy:
  #   image: caddy:2-alpine
  #   restart: unless-stopped
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   volumes:
  #     - ./caddy/Caddyfile:/etc/caddy/Caddyfile
  #   networks:
  #     - pub_web
  #     - pri_freq
  #   environment:
  #     - SITE_ADDRESS_2=${SITE_ADDRESS_2}

networks:
  pub_web:
    external: true
  pri_freq:
    external: false
    driver: bridge