---
version: '3'
services:
  live:
    build: .
    env_file: 
      - .env
    restart: unless-stopped
    volumes:
      - "./db:/freqtrade/user_data/db"
    command: >
      freqtrade trade -c live.json -c user_data/blacklist-binance.json -c user_data/pairlist-volume-binance-busd.json
    ports:
      - "9999:9999"
    restart: always
